theme: jekyll-theme-minimal

name: VOD and Network System Administrator
title: Bhong Almeda
description: Bookmark this to keep an eye on my project updates!


#title: VOD and Network System Administrator
email: B_H_O_N_G_2002@yahoo.com

about_profile_image: images/15363312.jpg

plugins:
 - jekyll-seo-tag