theme: jekyll-theme-minimal

version: 0
darkmode: true
name: Bhong Almeda
title: VOD and Network System Administrator

email: B_H_O_N_G_2002@yahoo.com

github_username:  bhong2002
facebook_username: bhong.almeda

about_profile_image: images/15363312.jpg

about_content:
  Hi, my name's Bhong and I'm a VOD softwares and network system administrator. As well as administrating systems I also have experience making software and web apps.
  I am most skilled in: <mark>ARDUINO, Raspberry PI, Linux(debian), Python(flask) and Flutter.</mark>

content:
  - title: Present Work
    layout: list
    content:
      - layout: right
        title: TSI-ACSI(Sky Cable Contractor)
        sub_title: Field Service Technician (FST)
        caption: April 20, 2021 - up to present
 
 - title: Previous Work
    content:
      - layout: right
        title: Soundway Entertainment Inc. (Closed)
        sub_title: VOD/POS software support
        caption: February 2010 - April 2019

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Samson Technological Institute
        sub_title: Basic Electronics Service Technician
        caption: 1986
        
plugins:
 - jekyll-seo-tag
