#theme: jekyll-theme-minimal
theme: resume-theme

version: 0
darkmode: true

#site: Bhong Almeda
name: Bhong Almeda
title: VOD and Network System Administrator


#description: Bookmark this to keep an eye on my project updates!


#title: VOD and Network System Administrator
email: B_H_O_N_G_2002@yahoo.com
#website: https://bhong2002.github.io/bhong2002/

github_username:  bhong2002
facebook_username: bhong.almeda

about_profile_image: images/15363312.jpg

about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Bhong and I'm a VOD softwares and network system administrator. As well as administrating systems I also have experience making software and web apps.
  I am most skilled in: <mark>ARDUINO, Raspberry PI, Linux(debian), Python(flask) and Flutter.</mark>


content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: Project name
  #      link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      link_text: Link Text
  #      additional_links:
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-facebook
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      quote: >
  #         |# Short overview of the project (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: TSI-ACSI(Sky Cable Contractor)
        sub_title: _Field Service Technician (FST)_
        caption: April 20, 2021 - up to present
        link: http://www.tsi.com.ph
        
    content:
      - layout: right
        title: TSI-ACSI(Sky Cable Contractor)
        sub_title: _Field Service Technician (FST)_
        caption: April 20, 2021 - up to present
        link: http://www.tsi.com.ph        

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Samson Technological Institute
        sub_title: Basic Electronics Service Technician
        caption: 1986
#        quote: >
#          Short institution or course description (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description of qualification
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
#      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*




plugins:
 - jekyll-seo-tag
