# site: bhong2002
repository: bhong2002
theme: jekyll-theme-cayman

name: Rogelio 'BHONG' Almeda
title: VOD and Network System Administrator
email: B_H_O_N_G_2002@yahoo.com
website: http://bhong.servebeer.com