theme: jekyll-theme-minimal

version: 0
darkmode: true

#site: Bhong Almeda
name: Bhong Almeda
title: VOD and Network System Administrator


#description: Bookmark this to keep an eye on my project updates!


#title: VOD and Network System Administrator
email: B_H_O_N_G_2002@yahoo.com
#website: bhong2002.github.io/bhong2002/

github_username:  bhong2002
facebook_username: jekyll

about_profile_image: images/15363312.jpg

plugins:
 - jekyll-seo-tag